### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by fdeitelhoff** [Gregoor/syntactor#22]
I constantly get the following error message:

```
multi ./node_modules/react-scripts/config/polyfills.js ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js
Module not found: SyntaxD:\Git\syntactor\src\package.json (directory description file): SyntaxError: D:\Git\syntactor\src\package.json (directory description file): SyntaxError: Unexpected token . in JSON at position 0
```

I tried different machines with different settings. Overall I'm not quite sure what to do about it. The file package.json seems fine in my opinion. Maybe someone has a hint how to approach/solve this problem.

**Comment by Gregoor** [comment]
Oops, good catch! I shouldn't have symlinked the example file unless I wanted to exclude Windows users. Fix is on its way!

**Comment by fdeitelhoff** [comment]
Wow @Gregoor, great work!

Many thanks for the fast fix. Works like charm. And nice paper at the Salon des Refusés 2017. :)

**Comment by Gregoor** [comment]
Thankslots, very happy to hear that :)

I'll eventually continue work on this, so that it supports more languages than JSON.
